### ISSUE TITLE
[Feature Request] Allow mouse tracking to only read a specific axis.

### ISSUE THREAD

**Issue by MaliMiau** [Gemmstone/PyNGtuber#1]
Problem Description:
---
Currently, the mouse tracking reads the cursor position on both the vertical (Y) and horizontal (X) axes with no way to customize it. 

Proposed Solution:
---
Allow the user to select specifically what specific axis should be tracked. Ideally, it should be customizable per asset. 

Implementation Options:
---
- **Checkboxes:** Add two independent checkboxes, one for each axis.
- **Dropdown List:** Add a dropdown menu with options like "Track X," "Track Y," and "Track Both (default)."
- **Two "Scale" Options:** Add separate "Scale" options (like the current one) for the X and Y axes.

**Comment by Gemmstone** [comment]
![image](https://github.com/Gemmstone/PyNGtuber/assets/31828821/e8642885-a2b4-4806-bb0e-08cea0099336)

**Comment by Gemmstone** [comment]
Done! :) 
It's ready in the version 1.5.1: https://github.com/Gemmstone/PyNGtuber/releases/tag/v1.5.1

**Comment by Gemmstone** [comment]
Ups, deleted the release by accident, fixing it!

**Comment by Gemmstone** [comment]
Sorry, [1.5.2](https://github.com/Gemmstone/PyNGtuber/releases/tag/v1.5.2)
