### ISSUE TITLE
Opening the software with a webcam plugged in causes the software to crash

### ISSUE THREAD

**Issue by TTTaevas** [Gemmstone/PyNGtuber#24]
Hello!

When I open PyNGtuber v1.10.1 on Linux (downloaded from itch.io) with a webcam plugged in, the software simply ends up crashing
If I unplug my webcam and try to open it again, the software works as expected
[log_start.txt](https://github.com/user-attachments/files/16836987/log_start.txt)

Similarly, if I plug in my webcam while the software is opened, _setting_ the camera number to 0 will cause it to crash
Changing that setting while the webcam is not plugged in doesn't crash the software
[log_camera0.txt](https://github.com/user-attachments/files/16836988/log_camera0.txt)

Please feel free to ask me for more information if that could help you fix this bug!

**Comment by Gemmstone** [comment]
Hey! thanks for reporting this!

Took a look at it and it has been fixed, expect it on the next version!

The issue was that PyInstaller wasn't adding some mediapipe files so I have to add them manually.

if the problem persists, there's a catch now so the software won't just crash lol

**Comment by Gemmstone** [comment]
Update released!

**Comment by Melonbwead** [comment]
I'm having the same issue on the latest released version Sep 14, after my app crashes I can't even open the app back up.

EDIT:
This is how I fixed it incase anyone run into the same issue, for my windows build navigate to your roaming folder:

`C(or whatever drive):\Users\<your user>\AppData\Roaming\PyNGtuber\Data`
Find the settings.json file and change the line `"mouse tracking": "face",` back to `"mouse tracking: "disabled",`

**Comment by Gemmstone** [comment]
> I'm having the same issue on the latest released version Sep 14, after my app crashes I can't even open the app back up.
> 
> EDIT: This is how I fixed it incase anyone run into the same issue, for my windows build navigate to your roaming folder:
> 
> `C(or whatever drive):\Users\<your user>\AppData\Roaming\PyNGtuber\Data` Find the settings.json file and change the line `"mouse tracking": "face",` back to `"mouse tracking: "disabled",`

Hey, yeah, face tracking on windows doesn't work atm, tbh it shouldn't show the option but alas, i'm working on an alternative way to do face tracking and yes, that's the correct fix.
