### ISSUE TITLE
Cant use my microphone

### ISSUE THREAD

**Issue by doctorbrew** [Gemmstone/PyNGtuber#26]
I am having issues with using any audio input device.
All I get in console is "An error occurred: [Errno -9985] Device unavailable
Error in audio stream: [Errno -9985] Device unavailable"

Oh and I am using linux

**Comment by doctorbrew** [comment]
Ah I missed this part of the console output:
Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1742

Expression 'AlsaOpen( &alsaApi->baseHostApiRep, params, streamDir, &self->pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1909

Expression 'PaAlsaStreamComponent_Initialize( &self->capture, alsaApi, inParams, StreamDirection_In, NULL != callback )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2173

Expression 'PaAlsaStream_Initialize( stream, alsaHostApi, inputParameters, outputParameters, sampleRate, framesPerBuffer, callback, streamFlags, userData )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2842

Must be a problem with alsa on my system then?

**Comment by Gemmstone** [comment]
Hey, could you try changing the audio engine in the settings? 
PyAudio doesn't pair with some computers so there's SoundDevice there too (the inverse is also true lol)!
Let me know if that fixes it!

**Comment by doctorbrew** [comment]
Sorry, I have been a away for some time, SoundDevice did work ^.^
I guess I'll mark this as closed.  Thank you for the help!
